include theos/makefiles/common.mk

BUNDLE_NAME = darkcctoggle
darkcctoggle_FILES = Switch.x
darkcctoggle_FRAMEWORKS = UIKit
darkcctoggle_LIBRARIES = flipswitch
darkcctoggle_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk